## A project name for naming summary files
project: "test"

## Input files
reference: "test_data/test_mutated.fasta"
sample_sheet: "test_data/sample_sheet.csv"
outdir: "test_variant_calling"

## Docker image path
clara-parabricks: "docker://nvcr.io/nvidia/clara/clara-parabricks:4.6.0-1"

## Some parameters
### window size for calculating coverage
w_size: 100000
### number of intervals to call variants independently as gatk don't do parallelism by default
split_n: 100
### memory limit for EACH interval (Gb)
memory_gb_per_interval: 1

## Filtering parameters
gq_min: 20
qual_min: 30
dp_max: 50
f_missing_max: 0.5
